### ISSUE TITLE
select2 localization isn't included

### ISSUE THREAD

**Issue by epaminond** [spree-contrib/spree_i18n#362]
As Spree uses select2-rails it should also be localized. [select2-rails](https://github.com/argerim/select2-rails) page recommends to 
add the following to `app/assets/javascripts/application.js`: `//= require select2_locale_"any possible language"`.

Can it be done by spree_i18n? :)

**Comment by KaurBaljeet** [comment]
Hello @radar  , i am using spree for my product, and i want to tag the product taxons which are assigned to that product previously. When i am clicking on edit product then there are not any single taxons showing related to that product. Please tell me how i can do this, or how i can modify the select2 to do this.
