### ISSUE TITLE
Incompatible encodings when my locale includes chi

### ISSUE THREAD

**Issue by arthurtalkgoal** [spree-contrib/spree_i18n#396]
I got an encoding errors in select avaiable locales when I include chinese 中文

Encoding::CompatibilityError in Spree::Admin::GeneralSettings#edit
Showing /home/railsu/.rvm/gems/ruby-2.0.0-p353@rails4/bundler/gems/spree-0e0c860c6292/backend/app/views/spree/admin/general_settings/edit.html.erb where line #27 raised:

Incompatible character encodings: ASCII-8BIT and UTF-8
Extracted source (around line #27):
24
25
26
27
28
29
30

```
 <div class="field">
   <label for="available_locales_"><%= Spree.t(:'i18n.available_locales') %></label>
   <%= select_available_locales %>
```

   </div>

**Comment by jasonfb** [comment]
re-opening at new issue https://github.com/spree/spree/issues/5889
