### ISSUE TITLE
Reversed translation when mixing RTL with LTR languages

### ISSUE THREAD

**Issue by Alshurafa** [spree-contrib/spree_i18n#428]
I am working on an Arabic translation, the old one on locale is a machine translation that is often inaccurate. Some words such as Spree and SSL if translated would become meaningless and should remain in English. But I found out that the translation is displayed in different order. It looks like Spree_i18n switches the RTL text at the beginning of the string with the one at the end when non RTL characters are in the middle. In fact, Spree_i18n isn't really reordering the text; it is just displaying the text the way it is saved.

This is a well known issue in most software projects that is caused by the fact that RTL text is displayed from right to left but is stored as left to right by default. Adding LTR text in between RTL text will split the RTL text into 2 units. I confirmed the issue on other RTL translations such as Farsi. I made sure that the yml file produced by locale stores correctly. This issue is actually being produced by Spree regardless if Spree_i18n extension is installed or not. But since Spree_i18n is the official internationalization extension to spree. It should be the project addressing this issue.

Screenshot from spree menu panel:
![reverse_translation](https://cloud.githubusercontent.com/assets/103536/3528151/40420e96-078c-11e4-899e-757851d05a66.png)
This is how the translation look like in Locale [[Link](http://www.localeapp.com/projects/4605/translations/2673411?in_locale=21085)]:
![correct_translation](https://cloud.githubusercontent.com/assets/103536/3528954/68b27a70-0794-11e4-89bf-da262665c75c.png)
This is how the text is stored:
"السماح باستخدام SSL في وضع التطوير والاختبار"
Github also have the same issue but try to copy the text and paste it into the address bar  or to google search bar and notice how the order is different.

**Comment by diff-** [comment]
Like!
Please support for RTL
Or at least more details on How-To make it RTL properly by own

**Comment by alepore** [comment]
@diff- if think this is an improvement that should be done by someone that actually knows how to manage RTL languages on the web.
Most people knowledge of the topic stops at:

```html
<body dir="rtl">
```
