### ISSUE TITLE
products with localized slugs always "not found" in admin

### ISSUE THREAD

**Issue by paolochiodi** [spree-contrib/spree_i18n#452]
Hi, I have a product with a localised slug, that is `slug_en` for english locale and `slug_it` for italian locale.
In the admin area, when navigating with the italian locale and trying to edit the product I always receive a "product not found" error message.

When rendering the view the locale has been correctly set and the product url contains `slug_it`, but when trying to load the product the locale is set to `:en` (the default one).

I think the problem is that the `set_user_language` before filter is executed after the before filter in the `Spree::Admin::ProductsController` that load the actual product.
What about using `prepend_before_filter`?

I'm using:
Spree 2.3.2
Spree_i18n, branch: 2-3-stable

**Comment by Wooobee** [comment]
I have the same problem with  Spree 2-2-stable. But changing the language back to default doesn't help.
Does anybody have a solution for this?

Best Manuel

**Comment by kumardev** [comment]
I am still facing this issue . Steps to reproduce -

1) Adding a custom slug field on Spree Product
2) Editing the Product
3) Updating the slug
4) The show page says product not found

On further digging , the slug comes in the url due to which proper redirection isn't taking place . Any fixes for this yet  ?

**Comment by kumardev** [comment]
Ok , so i was able to solve this by replacing :history with :finders as following

    friendly_id :name, use: [:slugged, :finders]
