### ISSUE TITLE
Doesn't work; locale getting reset in between the controller and the view.

### ISSUE THREAD

**Issue by george-carlin** [spree-contrib/spree_i18n#460]
I can't get this gem to work despite following the most simple instructions in a brand new Rails app.

You can see my minimal app which replicates the problem [here](https://github.com/georgemillo/spree_i18n_fail)

Here are the steps that I followed:

```
rails _4.1.4_ new spree_i18n_fail
spree install --auto-accept

# Added the following line to my Gemfile and ran bundle install
gem 'spree_i18n', :git => 'https://github.com/spree/spree_i18n.git', :branch => '2-3-stable'

rails g spree_i18n:install

# Added the following lines to ApplicationController:

before_action :set_locale

def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
end

#  Started the server
```

aaaaaand it doesn't work. No matter what I provide as "locale" in the URL param, my site always appears in English.

Tellingly, if I edit ApplicationController#set_locale to this:

```
def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
  puts "locale 1: #{I18n.locale.to_s}"
end
```

and copy over a view from `spree_frontend` into my own app (as you can see I've done in my minimal app with `app/views/spree/products/show.html.erb`), and add the line:

```
<% puts "locale 2: #{I18n.locale.to_s}" %>
```

and visit the requisite page with the "?locale=fr" parameter, when I look in the server log I see:

```
locale 1: fr
locale 2: en
```

So it appears that, somewhere between `ApplicationController#set_locale` and the view being rendered, the locale is being reset back to **en** from **fr**.

Am I doing something wrong, or is this a bug? Whatever the case, the documentation for this gem needs to be clearer. (I'll gladly submit a PR for the documentation myself once I've figured out what the actual problem is.)

**Comment by docelic** [comment]
I had the same issue that I managed to resolve.

In the beginning, I was setting everything in my app/controllers/application_controller.rb:

before_action :set_locale
def set_locale
    I18n.locale=
      Spree::Frontend::Config[:locale]=
      Spree::Backend::Config[:locale]=
        Rails.application.config.i18n.locale= :en
end

But nothing worked, until I found the file core/lib/spree/core/controller_helpers/common.rb in which there is another before_filter called set_user_language. That filter re-sets the locale only to the value of session[:locale], or if that's not defined, it goes directly to using the default.

So the solution is not to set I18n.locale, or frontend or backend locale in the before_filter, but just to set  session[:locale] = :LOCALE .

Hope it helps!
