### ISSUE TITLE
Better default locale setting strategy

### ISSUE THREAD

**Issue by alepore** [spree-contrib/spree_i18n#488]
We currently set the locale in the session.
This is openly discouraged in the [rails documentation](http://guides.rubyonrails.org/i18n.html#setting-and-passing-the-locale) and more in general i think it's not suitable for any real production site (who said SEO?).

Imho a better default may be setting locale from urls like `www.example.com/it/`, [refinerycms-i18n](https://github.com/refinery/refinerycms-i18n/) should be doing this very well, using the [routing-filter](https://github.com/svenfuchs/routing-filter) gem.
There's also [route_translator](https://github.com/enriclluelles/route_translator) to look at.

This was briefly discussed here https://github.com/spree-contrib/spree_i18n/issues/13#issuecomment-1629622

What do you think?

**Comment by alepore** [comment]
what i really like of `routing-filter` is that wraps the complex rails routing without touching it at all.
on `www.example.com/it/page` it will basically read the `/it`part, remove it, pass the clean url to rails, and then re-add the `/it` as last thing.

i'm using this in production right now, will follow up on this

**Comment by JDutil** [comment]
I'm fine with that.

**Comment by huoxito** [comment]
thanks for raising the issue and looking into it @alepore, did you ever get a chance to push any code related?

**Comment by alepore** [comment]
@huoxito ok, will add some code soon
