### ISSUE TITLE
add_translations_to_product_properties performance nightmare

### ISSUE THREAD

**Issue by javereec** [spree-contrib/spree_i18n#502]
I'm running a product site that contains a reasonable amount of product_property items (about 350k). When running the migration `20141112121313_add_translations_to_product_properties.rb`, the `{ migrate_data: true }` causes it to run like ... forever.

I've set the flag to `false` and performed the following, which I hope has the same end result.

```
insert into spree_product_property_translations (spree_product_property_id, value) (select id, value from spree_product_properties);
update spree_product_property_translations set locale = 'nl';
```

Replace the 'nl' with the default locale (`I18n.default_locale`) and execute raw sql statements. What do you think?

**Comment by JDutil** [comment]
Feel free to submit a PR to improve migration performance, but the sql must work properly against sqlite3, mysql, and postgres.

**Comment by JDutil** [comment]
I'm going to close this out as a question rather than an issue.
