### ISSUE TITLE
3-0-stable branch

### ISSUE THREAD

**Issue by joseramonc** [spree-contrib/spree_i18n#509]
Hi, I'm kind of new contributing to spree, and I'm wondering if I'm missing something (or if I can help), because I can't find the 3-0-stable branch for this repo, I want to install spree-3-0 from scratch and add this gem to it but I cant find it's corresponding branch.

Thanks in advice.

**Comment by arthurtalkgoal** [comment]
I got the error if I install spree_i18n with ```3-0-stable spree```

```
    spree_i18n (>= 0) ruby depends on
      friendly_id (~> 5.0.4) ruby

    spree_i18n (>= 0) ruby depends on
      friendly_id (5.1.0)

```

**Comment by JDutil** [comment]
There was a known issue with globalize we needed to bump the version for once it was released this weekend.  Now there are still 5 or so failing specs. Whenever the specs are fixed we will create the 3-0-stable branch.  In the meantime you can just use the master branch.

**Comment by joseramonc** [comment]
@JDutil thank you, now I'm able to use it with branch master, but I'm not able to create, properties, taxons or taxonomies, nor through the interface or from the rails console.

The error when saving those models is:

    Field 'name' doesn't have a default value: INSERT INTO `spree_taxonomies` (`created_at`, `updated_at`, `position`) VALUES ('2015-02-16 20:54:19.752967', '2015-02-16 20:54:19.752967', 1)

I was able to create records for those models by removing `, null: false` when creating those tables in the migration: https://github.com/spree/spree/blob/master/core/db/migrate/20120831092320_spree_one_two.rb#L385 
https://github.com/spree/spree/blob/master/core/db/migrate/20120831092320_spree_one_two.rb#L392
https://github.com/spree/spree/blob/master/core/db/migrate/20120831092320_spree_one_two.rb#L286

but I'm not sure if that's the correct approach to solve this problem

**Comment by joseramonc** [comment]
I'm also not able to do some queries by name. 

    Spree::Taxon.find_by_name('taxon')
    `Spree::Taxon Load (0.4ms)  SELECT  `spree_taxons`.* FROM `spree_taxons` INNER JOIN `spree_taxon_translations` ON `spree_taxon_translations`.`spree_taxon_id` = `spree_taxons`.`id` WHERE `spree_taxon_translations`.`name` = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}\n' AND `spree_taxon_translations`.`locale` = 'en' LIMIT 1`
    => nil

    Spree::Property.find_by_name('property')
    Spree::Property Load (0.4ms)  SELECT  `spree_properties`.* FROM `spree_properties` INNER JOIN `spree_property_translations` ON `spree_property_translations`.`spree_property_id` = `spree_properties`.`id` WHERE `spree_property_translations`.`name` = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}\n' AND `spree_property_translations`.`locale` = 'en' LIMIT 1
    => nil

    Spree::OptionValue.find_by_name('option value')
    Spree::OptionValue Load (0.9ms)  SELECT  `spree_option_values`.* FROM `spree_option_values` INNER JOIN `spree_option_value_translations` ON `spree_option_value_translations`.`spree_option_value_id` = `spree_option_values`.`id` WHERE `spree_option_value_translations`.`name` = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}\n' AND `spree_option_value_translations`.`locale` = 'en' LIMIT 1
    => nil

**Comment by JDutil** [comment]
This would be one of the other known failures... If you have a fix for them please submit a PR otherwise I'm not sure when I'll be able to resolve these.

**Comment by joseramonc** [comment]
Thank you, I'm going to try it out, do you have any advice of where in the code should I be looking into that issue?On Mon, Feb 16, 2015 at 11:06 PM,  Jeff Dutil <notifications@github.com> wrote:            This would be one of the other known failures... If you have a fix for them please submit a PR otherwise I'm not sure when I'll be able to resolve these.

**Comment by JDutil** [comment]
Sorry misread this last night I'm not sure what those errors are.  You can see the ones I'm talking about if you run the spec suite. I have no idea where to look on either of these issues, but I suspect it's another globalize issue.

**Comment by JDutil** [comment]
Just pushed 3-0-stable branch.

**Comment by joseramonc** [comment]
Thank you :+1: , I confirm that I'm able to create records, but still generates `find_by_name` queries wrong.

**Comment by JDutil** [comment]
I'm pretty sure rails deprecated find_by queries, and you shouldn't be using them anymore.

**Comment by joseramonc** [comment]
According to [rails/activerecord-deprecated_finders](https://github.com/rails/activerecord-deprecated_finders) readme and [rails guides](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2), `find(primary_key)`, `find_by...`, `find_by...!` are still not deprecated, only the old_style finders:

* `find_all_by_...`
* `find_last_by_...`
* `scoped_by_...`
* `find_or_initialize_by_...`
* `find_or_create_by_...`

Is there something I'm missing?

**Comment by JDutil** [comment]
Oh I thought it was all find_by not just find_all_by find_last_by.  So there was a change in globalize 5 though where they no longer store info on that record in the database it's all stored in the translations table.  So your query doesn't check the write table.  Use the where syntax, and it should properly query the translation table through the association I believe.

**Comment by joseramonc** [comment]
:+1: The where query is working, I'll be using it for now. Thanks for your help and for this great project
