### ISSUE TITLE
config.i18n.fallbacks doesn't work

### ISSUE THREAD

**Issue by tnj** [spree-contrib/spree_i18n#510]
When you set `config.i18n.default_locale = :your_preferred_locale_except_en` , you may also want to set `config.i18n.fallbacks = [:en]` since Spree's all resources are based on `:en`, or you'll see bunch of "Translation missing" that can causes broken tags.

However, current spree_i18n forces the property to `true` on the code, which means default_locale, so you can't make it fallback to `:en`.

https://github.com/spree-contrib/spree_i18n/blob/master/lib/spree_i18n/engine.rb#L20

Any ideas about this? I think that just removing this line is fine. At least, it shouldn't be `true` by default because it makes harder to find missing translations. Rails only set this to `true` in environments/production.rb.

**Comment by JDutil** [comment]
I think the current defaults are the most sane for the project.  We default to en and say yes fallback to the default.  This project assumes that you will actually translate your default locale if it's not en.  You can set in your application which fallbacks you want to use if you don't want to fallback to your default.

For example to accomplish what you want you set:
config.i18n.default_locale = :your_preferred_locale_except_en
config.i18n.fallbacks = [:your_preferred_locale_except_en, :en]

I'm not sure what a better default setting would be to work for most people most of the time, and this seems pretty reasonable for people to change if they need to.

**Comment by tnj** [comment]
Hi JDutil,

I understand the design, but the problem I tried to point here is that current spree_i18n **overwrites** `i18n.fallbacks` with hardcoded value `true`, which means *fallback to default_locale*, so it completely ignores config value.
