### ISSUE TITLE
Invalid down migration on #update_all with Rails 4.x

### ISSUE THREAD

**Issue by cveneziani** [spree-contrib/spree_i18n#562]
Hello,

I tried to rollback spree_i18n migrations and it turned out that with Rails 4.x I experienced an error around this line (see [migration.rb](https://github.com/spree-contrib/spree_i18n/blob/master/lib/globalize/active_record/migration.rb#L133)):

```ruby
@model.update_all(fields_to_update, {id: translated_record['id']})
```

Rails 4.x accepts only one parameter (see [#update_all](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update_all)). I suggest this change:

```ruby
@model.where(:id => translated_record['id']).update_all(fields_to_update)
```

What do you think about this?

Cecile

**Comment by JDutil** [comment]
Looks fine to me if you want to submit a PR

**Comment by cveneziani** [comment]
I submitted a PR.

**Comment by futhr** [comment]
Add to `master` branch with 112901b43224ff20fc9892c9cdd80860b99a6a84

**Comment by cveneziani** [comment]
Thanks for your quick move.
