### ISSUE TITLE
Dependency on spree_core ~> 3.1.0.beta - bundle is failing

### ISSUE THREAD

**Issue by francoisyanick** [spree-contrib/spree_i18n#581]
I cannot install spree_i18n because it is looking for spree_core beta which is not available. Any suggestions?

$ bundle install
Updating git://github.com/spree-contrib/spree_i18n.git
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.0.1)

  In Gemfile:
    spree_core (= 3.0.1) ruby

    spree_core (~> 3.0.0) ruby

    spree_core (~> 3.0.0) ruby

    spree_i18n (>= 0) ruby depends on
      spree_core (~> 3.1.0.beta) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict. 

Thx

**Comment by tvdeyen** [comment]
Please use the 3-0-stable branch if you use spree 3.0. The master branch is for the master branch (3.1.0 beta) of spree.
