### ISSUE TITLE
How to customize locale_selector.html.erb.deface

### ISSUE THREAD

**Issue by mmintel** [spree-contrib/spree_i18n#584]
Hi there!

I am really new to spree and ruby and I just would like to know how I can customize that file.
My problem is that I want to change the markup position of the locale selector.

I tried to place a file with the same name in my app/overrides/spree/shared/_main_nav_bar but changes are ignored.

Could anybody help me please? Where do I need to put my changes?

**Comment by JDutil** [comment]
Placing the override file in the same path with the same name should work or you can try reviewing some of the deface documentation for alternatives https://github.com/spree/deface#redefining-overrides
