### ISSUE TITLE
Can I disable model-translation with spree 3-0-0-stable?

### ISSUE THREAD

**Issue by odk211** [spree-contrib/spree_i18n#611]
I will start to develop my application with spree 3-0-0-stable and spree_i18n now.
but, I do not need the model translation feature.
Can I disable this feature ?

I know spree_i18n remove model-translation feature at master branch.
but I do not know I can use it at 3-0-0-stable branch.

I'm not sure I should ask it here.
If it is better to ask with mailing list, I will move it.
Thanks !

**Comment by JDutil** [comment]
You should develop against the master branch then.  We split the model translation feature into spree_globalize on the master branch exactly for this reason.
