### ISSUE TITLE
Ransack Search by extra fields

### ISSUE THREAD

**Issue by iagomoreira** [spree-contrib/spree_i18n#623]
Hello! 
I was having problems with product searching on the admin area of spree, and it was because of the translations, solved by #602, then there was the problem with the whitelist (which was solved by #618). I updated my spree_i18n and those bugs are all fixed. But now, I'm experiencing a problem that I wasn't before. 

My Product model has some extra attributes, 
e.g `campaign` (which is a number) 
So in my product filter I added this (using deface override)
```
<div class="col-md-6">
  <div class="form-group">
    <%= f.label :campaign_eq, Spree.t(:campaign) %>
    <%= f.select :campaign_eq, 1..12,{ include_blank: true }, { class: "form-control" } %>
  </div>
</div>
```

It was work perfectly before updating those things due to the translation problems and right now I'm getting the error `undefined method campaign_eq for #<Ransack::Search:0x007ff6b2cf9120>` when I access the `products#index` page.

Is it a bug or a normal behaviour?  Did I miss some step? 

[UPDATE]
I added `translates :campaign` on my `Spree::Product` decorator and created a migration like 

```
class AddExtraFieldTranslationToProducts < ActiveRecord::Migration
  def up
    fields = { campaign: :string }
    Spree::Product.add_translation_fields!(fields, { migrate_data: true })
  end

  def down
  end
end
```

And I still have the problem `undefined method 'campaign_eq' for #<Ransack::Search:0x007feaab3ce810>`

**Comment by alepore** [comment]
You have to add your custom search fields to the whitelist, on a initializer, as stated here https://spreecommerce.com/blog/security-updates-2015-8-19

That's a breaking change on latest spree versions

**Comment by iagomoreira** [comment]
It worked! Thanks a lot!! :heart:

**Comment by w3villa-shubham** [comment]
@alepore this link is not working.  https://spreecommerce.com/blog/security-updates-2015-8-19
