### ISSUE TITLE
Missing Keys in Translation files

### ISSUE THREAD

**Issue by rposborne** [spree-contrib/spree_i18n#635]
It appears the german translation file is out of sync with 3.0-stable.   (lots of keys that are present in en.yml on spree/spree are not present in the de.yml. I have spot check a few other translation files and they seem to lack those keys as well. 

https://github.com/spree/spree/blob/3-0-stable/core/config/locales/en.yml#L1351-L1353

I am looking at the 3-0 stable branch for spree_i18n

It looks like you all have facilities to sync translations from spree head?  How often do these rake tasks get run?

**Comment by rposborne** [comment]
So it's pretty clear this isn't used much / at all, the custom YAML Comments parser has a huge amount of edge cases that fail when a singular key becomes a hash from upstream.  

Also am not sure if the behavior of inserting the english key is desired?

**Comment by futhr** [comment]
@rposborne hi, its best to leave untranslated keys empty so they can do proper fallback.

**Comment by rposborne** [comment]
@futhr understood.   I think we should generally drop the custom YAML parser as well? Do you know it's history.  It looks to attempt to preserve comments, but I can't find any comments in our .yml files

**Comment by futhr** [comment]
@rposborne Probably a good idea.

**Comment by JDutil** [comment]
:+1: on dropping any legacy tasks that don't work as they should. We don't usually run any sort of rake tasks that I know of using, we just accept PR's to improve a locale and will cherry-pick changes across branches where appropriate.

**Comment by JDutil** [comment]
Going to close this out as a question.  Please feel free to submit PR's improving any locales you want.

**Comment by rposborne** [comment]
@JDutil we will work to get a PR for a rake task to ensure yaml file consistency but, I don't think this issue is closed. Most translations are incomplete, and there is no meaningful way for a user / translator to determine this without keys being present.  Browsing a given translation with keys that are no longer in use  or worse a string that is now nested upstream provide a false sense of completeness for that locale.
