### ISSUE TITLE
Lost translations after upgrade to 3-1-stable

### ISSUE THREAD

**Issue by mmintel** [spree-contrib/spree_i18n#679]
Hi there,

since I have updated my project to use all latest spree gems I am missing my translations.
For updating I had to run this command `bundle exec rake railties:install:migrations` to get these migrations here:
<img width="598" alt="screen shot 2016-06-01 at 11 47 49" src="https://cloud.githubusercontent.com/assets/4574612/15705285/ded6108c-27ee-11e6-91a5-9045ba2e80cc.png">
and now I am missing my translations and also the "Translations" tab in the product menu:
<img width="541" alt="screen shot 2016-06-01 at 11 49 31" src="https://cloud.githubusercontent.com/assets/4574612/15705304/f1678014-27ee-11e6-8d47-fcb0f817e310.png">

Somebody knows what happened? Do you have a solution?

**Comment by tvdeyen** [comment]
We moved the model translations into the `spree_globalize` gem [as noted here](https://github.com/spree-contrib/spree_i18n#model-translations)

**Comment by mmintel** [comment]
Ah the problem was I only added "gem globalize" and not "gem spree_globalize", thanks!

**Comment by tvdeyen** [comment]
👍
