### ISSUE TITLE
AssetNotFound in Spree::Admin::Orders#index

### ISSUE THREAD

**Issue by htorohn** [spree-contrib/spree_i18n#734]
When setting the default locale on application.rb to 'es-MX', I'm getting the following error when trying to get into /admin:

The asset "select2_locale_es-MX.js" is not present in the asset pipeline.

for the frontend the default locale is working perfect, but for the backend it raises that error.

--------------- This is my Gemfile ------------------------------------

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.3'

gem 'mysql2', '>= 0.3.18', '< 0.5'

gem 'puma', '~> 3.7'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.2'

gem 'turbolinks', '~> 5'

gem 'jbuilder', '~> 2.5'

group :development, :test do
  gem 'capistrano', '~> 3.7', '>= 3.7.1'
  gem 'capistrano-rails', '~> 1.2'
  gem 'capistrano-passenger', '~> 0.2.0'
  gem 'capistrano-rake', require: false
  gem 'capistrano-rbenv', '~> 2.1'
end 

group :development, :test do
gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do

  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'spree', '~> 3.3.0.rc1'
gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'

gem 'spree_simple_theme', github: 'htorohn/spree_simple_theme'

gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content'

gem 'font-awesome-rails', '~> 4.7', '>= 4.7.0.2'

----------------------- This is my application.rb file ---------------

> require_relative 'boot'
> 
> require 'rails/all'
> 
> # Require the gems listed in Gemfile, including any gems
> # you've limited to :test, :development, or :production.
> Bundler.require(*Rails.groups)
> 
> module Myshop
>   class Application < Rails::Application
>     
>     config.to_prepare do
>       # Load application's model / class decorators
>       Dir.glob(File.join(File.dirname(__FILE__), "../app/**/*_decorator*.rb")) do |c|
>         Rails.configuration.cache_classes ? require(c) : load(c)
>       end
> 
>       # Load application's view overrides
>       Dir.glob(File.join(File.dirname(__FILE__), "../app/overrides/*.rb")) do |c|
>         Rails.configuration.cache_classes ? require(c) : load(c)
>       end
>     end
> 
>     # Initialize configuration defaults for originally generated Rails version.
>     config.load_defaults 5.1
> 
>     #Idioma por defecto
>     **config.i18n.default_locale = 'es-MX'**
> 
>     # Settings in config/environments/* take precedence over those specified here.
>     # Application configuration should go into files in config/initializers
>     # -- all .rb files in that directory are automatically loaded.
>   end
> end
>

**Comment by justinemar** [comment]
This error still persists.

**Comment by kinduff** [comment]
Able to reproduce, I'm having the same error with the same Spree version.

**Comment by kinduff** [comment]
I did my homework: This is not an issue with `spree_i18n`, I was able to trace it back to the gem `select2-rails`, they're missing with the `es-MX` locale file since they just have the `es` one.

I was able to fix this issue by copying and pasting [this file](https://github.com/argerim/select2-rails/blob/master/vendor/assets/javascripts/select2_locale_es.js) into my `vendor/assets/javascripts` using the filename `select2_locale_es-MX.js`. This is a temporary solution until `select2-rails` and `spree` are updated.

This issue should be closed.

**Comment by htorohn** [comment]
Thank you very much Kinduff!!

**Comment by Uriel7** [comment]
Thank you @kinduff ;)

**Comment by iwano** [comment]
I had to name it "select2_locale_es-Mx.js" with lowercase x for it to work.

Thanks Kinduff!

**Comment by Janee** [comment]
If anyone finds this issue on `spree v3.7.3`, the temp solution still the one who @kinduff told.

🙌 Thanks, @kinduff!
