### ISSUE TITLE
Cannot be used when spree version is 3.1.0 or more and less than 3.7.0

### ISSUE THREAD

**Issue by yamamoto1089** [spree-contrib/spree_i18n#827]
I using Spree version 3.2.7.

The version of spree_core described in spree_i18n.gemspec of the master branch is `'spree_core','>= 3.7.0','< 5.0'`, so it seems that it cannot be used in the case of spree version 3.7.0 or lower.
Similarly, the version of spree_core described in the stable version 3-1-stable of spree_i18n.gemspec is `'spree_core','~> 3.1.0.beta'`, so it cannot be used in case of spree version 3.1.0 or higher. 

I want to use it even if the version of spree is 3.1.0 to 3.7.0.

**Comment by damianlegawiec** [comment]
@yamamoto1089 thanks for reporting, the issue should be fixed by noiw
