### ISSUE TITLE
Swedish translation improvements

### ISSUE THREAD

**Issue by githubble01** [spree-contrib/spree_i18n#854]
The Swedish translation has some points of improvement
- Improve semantic correctness and consistency regarding the terminology.
- Add translations for compatibility with spree 4.1.

**Comment by damianlegawiec** [comment]
@githubble01 could you create a PR with those improvements? My Swedish is really lacking ;)

**Comment by githubble01** [comment]
> @githubble01 could you create a PR with those improvements? My Swedish is really lacking ;)

Done! 😄

**Comment by damianlegawiec** [comment]
Thank you @githubble01 💪
