### ISSUE TITLE
uninitialized constant SpreeI18n::LocaleHelper

### ISSUE THREAD

**Issue by mgcostaParedes** [spree-contrib/spree_i18n#863]
Hi, after installing the package i am getting the following error visiting the url admin/stores:

can someone explain what is wrong or missing?

<img width="977" alt="Screenshot 2021-01-20 at 22 50 13" src="https://user-images.githubusercontent.com/16031444/105250552-dcdf8400-5b71-11eb-94f3-711a17b3bf95.png">

Thank you!

**Comment by damianlegawiec** [comment]
@mgcostaParedes please update your spree version to 4.2.0.rc4
