### ISSUE TITLE
install spree_i18n nothing wrimg

### ISSUE THREAD

**Issue by 121213tjfgalfjaf** [spree-contrib/spree_i18n#867]
the gem file 
![image](https://user-images.githubusercontent.com/5094727/106378234-13bd6180-63de-11eb-96f1-3a3642459768.png)

bundle update 
bundle install

bundle exec rails g spree_i18n:install

![image](https://user-images.githubusercontent.com/5094727/106378257-42d3d300-63de-11eb-8833-b83989112dce.png)

the result as above.

**Comment by damianlegawiec** [comment]
That installer is now obsolete, it's needed for previous versions though, that's why it still in the README
